### ISSUE TITLE
Improvment

### ISSUE THREAD

**Issue by Angeloxx92** [embyt/enocean-mqtt#11]
Dear romor ,
I've developed an asynchronous version of [Python EnOcean](https://github.com/kipe/enocean) built on asyncio. The High level API are the same of the previous library, but low level everything runs in an asynchronous thread so the performance are better. If you are interested take a look.
[enocean_async](https://github.com/Angeloxx92/enocean_async)

**Comment by romor** [comment]
Thanks for the info. Looks promising.
