### ISSUE TITLE
Unable to control D2-05 Blinds control for position and angle

### ISSUE THREAD

**Issue by hhenkel** [embyt/enocean-mqtt#17]
I'm trying to control my [Nodon Roller Shutter Module](https://nodon.fr/en/nodon/the-enocean-roller-shutter-module/) working with enocean-mqtt. So far I'm able to receive messages via mqtt but I'm not able to set the position of the roller shutter when following the [README](https://github.com/embyt/enocean-mqtt#answering-enocean-messages). I'm not sure where the problem is - I guess my "default_data" part is wrong but I'm currently struggling what the "correct" data would be. Maybe you can help clarify how this value is calculated and update the README?

I added some debug messages to your code to get a better understanding of what is going on. I'm able to see that your code is receiving my requests from the mqtt broker and is setting the data for the sensor, but I'm not sure if a enocean message is triggered after this step. Can you clarify if this is implemented and should work?

My config for the roller shutter module looks like this:
```
[shutter]
address = 0x051C1FB7
rorg = 0xd2
func = 0x05
type = 0x00
log_learn       = 1
publish_rssi    = 1
persistent = 1
answer          = 1
default_data    = 0x32790008
```

**Comment by hhenkel** [comment]
@romor thanks for your honest feedback to my request. I was looking at nodered with the enocean-js based plugin to solve my issue. However after debugging nodejs code I can say that code has some flaws of its own.

I'm with you, that it might be a useful extension of your project, but my current guess is, that this will lead to some major rework and additional implementation work in the underlying python library. In my opinion it would be nice if the library and your code would work in a more general way, automatically based on the available docs from enocean.

I'm yet undecided how to solve my issue - as I just want to get my few devices working... ;)

We can close the issue if you like or leave it open for reference for now.

**Comment by romor** [comment]
I just did an implementation of that feature.

To use it:
* checkout the feature branch `packet_sending`
* adapt the config file: look at the sample; mainly you only need to set the destination address
* set the desired RF data content via MQTT messages to  \<sensor\>/req/\<topic\>, as before
* to invoke packet sending, publish any MQTT message to \<sensor\>/req/send

Please notice, that this is not tested at all. Please expect problems, potentially even syntax errors.
Looking forward to your feedback.

**Comment by markuslindenberg** [comment]
I might soon (hopefully next week) be able to test this with a bunch of Becker Enocean blind drives, which support D2-05-02 and according to the manufacturer are 100% compliant.
I'm planning to integrate them in Home Assistant, looking at the very basic state of HA's native enocean support I guess enocean-mqtt is the way to go.

See https://www.becker-antriebe.com/fileadmin/user_upload/Downloads/Rolllaeden/Antriebe/n01_2010_301_120_0_de.pdf for reference.

**Comment by romor** [comment]
Branch `packet_sending` is merged to master and should provide the function needed.
