### ISSUE TITLE
More examples needed in the documentation

### ISSUE THREAD

**Issue by rnusser** [embyt/enocean-mqtt#24]
Firstly, thanks for this great module. It worked straight out of the box and mqtt messages were published as soon as I turned on the lights!

However I am finding certain parts of the setup a bit difficult to understand, regarding controlling the lights. 

In debug mode I do get a load of information: (pressing the lights switch button once without letting go)
```
2021-09-10 17:18:33,396 DEBUG: FE:F8:CA:48->FF:FF:FF:FF (-92 dBm): 0x01 ['0xf6', '0x30', '0xfe', '0xf8', '0xca', '0x48', '0x30'] ['0x0', '0xff', '0xff', '0xff', '0xff', '0x5c', '0x0'] OrderedDict()
2021-09-10 17:18:33,400 INFO: received: FE:F8:CA:48->FF:FF:FF:FF (-92 dBm): 0x01 ['0xf6', '0x30', '0xfe', '0xf8', '0xca', '0x48', '0x30'] ['0x0', '0xff', '0xff', '0xff', '0xff', '0x5c', '0x0'] OrderedDict()
2021-09-10 17:18:33,423 DEBUG: enocean/passage_end: R1 (Rocker 1st action)=Button AO 
2021-09-10 17:18:33,431 DEBUG: enocean/passage_end: EB (Energy bow)=pressed 
2021-09-10 17:18:33,439 DEBUG: enocean/passage_end: R2 (Rocker 2nd action)=Button AI 
2021-09-10 17:18:33,447 DEBUG: enocean/passage_end: SA (2nd action)=No 2nd action 
2021-09-10 17:18:33,454 DEBUG: enocean/passage_end: T21 (T21)=True 
2021-09-10 17:18:33,464 DEBUG: enocean/passage_end: NU (NU)=True 
```

I would like to send this message to turn the lights on using MQTT. The document mentions `default_data`, in the hvac example: `default_data    = 0x32790008`, which I didn't understand at all. What is that data, and how do I work out what I need.

Also for the hvac example a message is sent to enocean/heating/req/SP which is "set point", what would that be in the case of the switch?

If reading the code using `hexdump -C < /dev/ttyAMA0` I see something like this:

55 00 07 07 01 7a f6 70 fe fa 41 49 30 00 ff ff ff ff 5b 00 0a

I suppose this somehow relates to that default_data?

Any help would be appreciated.

**Comment by romor** [comment]
Typically, an Enocean message contains multiple data bytes to transfer. To create its content, `default_data` is the starting point for the message. This can then be adapted using MQTT messages to customize various parts of the message based on the EEP data interpretation (e.g. changing the "set point" content of the data).

**Comment by rnusser** [comment]
So in my case it seems that telegrams from PTM transmitters F6-RPS EEP (Enocean telegram type for repeated switch communication) has it's data in the byte that follows 0xF6, being 0x30. After that there is the 4 byte address, and then another 1 byte for status (T21 = bit 7, NU = bit 6, RC (repeater count = 6 bits) 

So the byte 0x30 is the actual data containing the R1, EB, R2, and SA.

Is the `default_data` optional, or must it be defined. If it is optional could one form the entire message by sending all the information usually received:

```
mosquitto_pub -d -h 192.168.100.30 -p 1883 -t 'enocean/passage_end/req/R1' -m '1'
mosquitto_pub -d -h 192.168.100.30 -p 1883 -t 'enocean/passage_end/req/EB' -m '1'
mosquitto_pub -d -h 192.168.100.30 -p 1883 -t 'enocean/passage_end/req/R2' -m '0'
mosquitto_pub -d -h 192.168.100.30 -p 1883 -t 'enocean/passage_end/req/T21' -m 'True'
mosquitto_pub -d -h 192.168.100.30 -p 1883 -t 'enocean/passage_end/req/NU' -m 'True'
mosquitto_pub -d -h 192.168.100.30 -p 1883 -t 'enocean/passage_end/req/send' -m '1'
```

Or have I totally misunderstood that bit?

 I have tried but with no luck.

I have tried setting the default to 0x30 and 0xf610fef8ca4830.

**Comment by romor** [comment]
> Is the `default_data` optional, or must it be defined. If it is optional could one form the entire message by sending all the information usually received:

Right now, `default_data` is not optional. Good idea, to allow this in future.
However, you can just set it to zero and assemble the data content as you wrote.

> I have tried but with no luck.

Could you give more information here?
I assume the EnOcean packet is sent but with wrong content?
Which content is sent (you should see this in the debug log)?

**Comment by rnusser** [comment]
Well, I still have not managed to turn the lights on or off, so I am not quite sure what I might be missing or what is not working.

I might have to try the Python EnOcean library and see if i can get it working with that first.

**Comment by romor** [comment]
Closing this for now. Please reopen or file a more specific issue as needed.
