### ISSUE TITLE
Using Environment Variables 

### ISSUE THREAD

**Issue by duylong** [embyt/enocean-mqtt#28]
Hello,

It would be interesting to be able to use environment variables for certain options such as debug for example. I use them in a Docker environment. 

I did this while waiting in the enoceanmqtt.py file :
```
    if os.getenv('DEBUG') == True:
        conf['debug'] = True

    # setup logger
```

**Comment by duylong** [comment]
It would be interesting to specify the level logs to be displayed by default by an environment variable.

**Comment by romor** [comment]
Not sure about this.

There is already the configuration file for most settings as well as command line arguments like `--debug` for increased logging output. To introduce a third method for configuration might raise more confusion than benefit?
