### ISSUE TITLE
Setting status bits in send messages

### ISSUE THREAD

**Issue by LarsKoeppel** [embyt/enocean-mqtt#41]
Hello,

i use [HA_enoceanmqtt](https://github.com/mak-gitdev/HA_enoceanmqtt) which builds on enocean-mqtt to integrate and control my devices in Home Assistant. 
As described in [this discussion](https://github.com/mak-gitdev/HA_enoceanmqtt/discussions/65#discussioncomment-5830611), my shutter only seems to respond to messages that have the status bits set correctly. So my question is if it would be possible to implement this functionality in enocean-mqtt.

Best regards

**Comment by romor** [comment]
I read the discussion in the linked thread but I do not really understand what is missing.
The packet data are set using `set_eep()` in the underlying  [enocean library](https://github.com/kipe/enocean). 

Are the status bits present there in the EEP profile and supported?
It is not my intention to forward you one more time, but I guess this topic is more related to the [enocean library](https://github.com/kipe/enocean)?

**Comment by LarsKoeppel** [comment]
Hi @romor,

the status bits are present in the EEP and are requered from enocean. I used this [EEP](https://github.com/mak-gitdev/HA_enoceanmqtt/blob/be01b5e13ba2324a09ebe9006e5fc2289dd83971/enocean/protocol/EEP.xml#L41) with this [specification](http://tools.enocean-alliance.org/EEPViewer/profiles/F6/02/01/F6-02-01.pdf).
As can be seen in the debug output in the other discussion, the status bits are not taken into account in the array of data to be sent, which is why I assumed that it was already ignored when the message was created. Or is the message to be sent created in the enocean library? Is [this](https://github.com/kipe/enocean/blob/80a253bcea1e3cb99295f53f04c0558190dca5f3/enocean/protocol/packet.py#L284) methode used to generate the message to send?

This is the message from debug, in the other discussion:
```
['0xf6', '0x70', '0xff', '0xab', '0xf3', '0x1', '0x0']
[<EEP>, <data>, <sender>, <sender>, <sender>, <sender>, <status bits>]
```
And the status bits should be in this case a `0x30`.

**Comment by mak-gitdev** [comment]
Hi @romor, Hi @LarsKoeppel 

I think I found the problem.
The problem I think, comes from the `set_eep()` function.
It does not set the status bits of the packet.
The status bits have to be appended to the packet data in the same manner as it is done [here](https://github.com/kipe/enocean/blob/80a253bcea1e3cb99295f53f04c0558190dca5f3/enocean/protocol/packet.py#L240).

As we use ERP1 and its DATA structure is always [\<RORG>\<PAYLOAD>\<SENDER>\<STATUS>], we could solve this issue in communicator.py by adding after [L461](https://github.com/embyt/enocean-mqtt/blob/master/enoceanmqtt/communicator.py#L461)
```py
packet.data[-1] = packet.status
```

@romor, is this OK for you or do you have a better idea ?  If OK, do you want me to make the pull request ?

**Comment by romor** [comment]
@mak-gitdev, thanks for your support!

I still do not fully understand why the status bits are not set within `set_eep()`. Is this intentionally not done there or just missing?

However, I trust in your proposal and for me it's fine to add it here, even if it is a work-around. Feel free to raise a pull request.

**Comment by mak-gitdev** [comment]
@romor, I am as baffled as you are but I think it is done intentionally because in the `Packet.create()` function, the data payload is first set with the `set_eep()` function, then the status bits are set separately as aforementioned.

Ok for the pull request. Thanks.
