### ISSUE TITLE
Error in device selection when sending data

### ISSUE THREAD

**Issue by mak-gitdev** [embyt/enocean-mqtt#43]
Hi @romor,

Another issue has just been found.
Please have a look at mak-gitdev/ha_enoceanmqtt#73 for more details.

The problem is that in some cases, we select the wrong device for sending data.
This happens when two or more devices have very similar names as the device selection only checks whether the sensor name is **IN** the MQTT topic ([L135](https://github.com/embyt/enocean-mqtt/blob/master/enoceanmqtt/communicator.py#L135) and [L172](https://github.com/embyt/enocean-mqtt/blob/master/enoceanmqtt/communicator.py#L172))

One solution would be to add `/` at the end of the current sensor name when checking if the current sensor is the targeted one.
```python
if cur_sensor['name']+"/" in msg.topic:
```
This has been tested and effectively fixed the issue.

**Comment by romor** [comment]
Thanks for fixing this.
